baseurl = "/"
languageCode = "en-us"
title = "Analítica Blog"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"


[[menu.main]]
    name = "Acerca de"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Categorías"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.main]]
    name = "Suscribir"
    url = "/index.xml"


[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; Analítica, 2018 - [mail](mailto:matias.alfonso@gmail.com)"
    sitename = "AnalíticA"
